project:
  type: website
  output-dir: docs

website:
  title: "Introduction to RNAseq workshop"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - href: schedule.html
        text: "Schedule"
      - href: notebooks/1.0_casestudy.html
        text: "Case study"
      - text: "Day 1"
        menu:
        - text: "1.1 RNAseq experimental workflow"
          href: notebooks/1.1_rnaseq-experiment.html
        - text: "1.2 Data QC with nf-core/rnaseq"
          href: notebooks/1.2_nfcore-qc.html
        - text: "1.3 Data preprocessing with nf-core/rnaseq"
          href: notebooks/1.3_nfcore-run.html
        - text: "1.4 Read alignment and quantification"
          href: notebooks/1.4_alignquant.html
        - text: "1.5 Workflow performance"
          href: notebooks/1.5_outputs.html
        - text: "1.6 Session 1 wrap up"
          href: notebooks/1.6_wrapup.html
      - text: "Day 2"
        menu:
        - text: "2.1 RStudio for downstream analysis"
          href: notebooks/2.1_rstudio-downstream.html
        - text: "2.2 Exploratory analysis"
          href: notebooks/2.2_exploratory.html
        - text: "2.3 Differential expression analysis"
          href: notebooks/2.3_differentialex.html
        - text: "2.4 Functional enrichment analysis"
          href: notebooks/2.4_enrichment.html
        - text: "2.5 Workshop wrap up"
          href: notebooks/2.5_wrapup.html
      - text: "Tips & tricks"
        href: tipstricks.qmd
  cookie-consent: 
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

body-footer: "<div style='font-size: 14px;'>All materials copyright Sydney Informatics Hub, University of Sydney</div>"

format:
  html:
    theme: 
      light: flatly
    css: styles.scss
    toc: true
    highlight-style: github
    page-layout: full

